### ISSUE TITLE
Changes to TVGids.tv?

### ISSUE THREAD

**Issue by kyl416** [tvgrabbers/tvgrabnlpy#51]
For the past few days I've been getting some errors on TVGids.tv, the one thing in common is that it only appears on the Film1 and HBO channels, so it might be specific to movies:

```
2015-12-14 04:47:53 : Error processing tvgids.tv detailpage:http://www.tvgids.tv/tv/hollywood-banker/14702652
2015-12-14 04:47:53 : Traceback (most recent call last):
2015-12-14 04:47:53 :   File "tv_grab_nl.py", line 8482, in load_detailpage
2015-12-14 04:47:53 :     kw_val = d.find('div').get('class').strip()
2015-12-14 04:47:53 : AttributeError: 'NoneType' object has no attribute 'get'
2015-12-14 04:47:55 : Error processing tvgids.tv detailpage:http://www.tvgids.tv/tv/northpole/14702656
2015-12-14 04:47:55 : Traceback (most recent call last):
2015-12-14 04:47:55 :   File "tv_grab_nl.py", line 8482, in load_detailpage
2015-12-14 04:47:55 :     kw_val = d.find('div').get('class').strip()
2015-12-14 04:47:55 : AttributeError: 'NoneType' object has no attribute 'get'
2015-12-14 04:47:58 : Error processing tvgids.tv detailpage:http://www.tvgids.tv/tv/de-dolle-tweeling-3/14702662
2015-12-14 04:47:58 : Traceback (most recent call last):
2015-12-14 04:47:58 :   File "tv_grab_nl.py", line 8482, in load_detailpage
2015-12-14 04:47:58 :     kw_val = d.find('div').get('class').strip()
2015-12-14 04:47:58 : AttributeError: 'NoneType' object has no attribute 'get'
2015-12-14 04:48:01 : Error processing tvgids.tv detailpage:http://www.tvgids.tv/tv/the-birdcage/14702664
2015-12-14 04:48:01 : Traceback (most recent call last):
2015-12-14 04:48:01 :   File "tv_grab_nl.py", line 8482, in load_detailpage
2015-12-14 04:48:01 :     kw_val = d.find('div').get('class').strip()
2015-12-14 04:48:01 : AttributeError: 'NoneType' object has no attribute 'get'
2015-12-14 04:55:50 : Error processing tvgids.tv detailpage:http://www.tvgids.tv/tv/waar-is-het-paard-van-sinterklaas/14716775
2015-12-14 04:55:50 : Traceback (most recent call last):
2015-12-14 04:55:50 :   File "tv_grab_nl.py", line 8482, in load_detailpage
2015-12-14 04:55:50 :     kw_val = d.find('div').get('class').strip()
2015-12-14 04:55:50 : AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by hikavdh** [comment]
I've noticed and fixed it. It's a snippet I added to get kijkwijzer info from tvgids.tv, only sometimes while it is present it is empty :(
At present I'm working on adding an option to mail your log on completion. I have most of it worked out and I then also can use it to mail me any changes on the lineup on the sources. I hope to get a testversion ready tonight.
Also of late I have seen regularly incomplete reads. While the base pages mostly get a second try on failure, the detail pages don't. I'm thinking about a workable retry. I need a counter so it doesn't keep retrying endlessly and only on errors like 'incomplete read'.

**Comment by hikavdh** [comment]
https://github.com/tvgrabbers/tvgrabnlpy/releases/tag/beta-2.2.7-p20151214 
See the description there.
If you have also `write_info_files` set, a list of channel-lineup changes is also mailed. I might add others. You can set an alternative mail-address for these last through the `mail_info_address` variable.
